### ISSUE TITLE
UK - ARRIVAL

### ISSUE THREAD

**Issue by dmgower** [GowerStreet/Forecast_Estimates#1]
https://forecast-beta.gower.st/film?/?titleId=1961944&ter-id=UK&source=gsa

There is an issue with this title. Demographics are missing?

For now, can we copy the demographics from ELYSIUM?
https://forecast-beta.gower.st/film?/?titleId=1556494

**Comment by mebassett** [comment]
time has rendered this irrelevant, I think.
