### ISSUE TITLE
KEVIN HART: WHAT NOW [UK] is now NV

### ISSUE THREAD

**Issue by dmgower** [GowerStreet/Forecast_Estimates#3]
This title seems to be an NV (not viable, no release date) in the UK.

Please remove the date from the system.

![image](https://cloud.githubusercontent.com/assets/12038000/21264301/83914c46-c393-11e6-8c69-419b023f8e53.png)

![image](https://cloud.githubusercontent.com/assets/12038000/21264307/8eb297c4-c393-11e6-9bee-0808f91627e1.png)

**Comment by dmgower** [comment]
![image](https://cloud.githubusercontent.com/assets/12038000/21264371/d8e347da-c393-11e6-98bc-58c9435ae24e.png)

**Comment by mebassett** [comment]
ptn or gsaid would make these easier, please include them.

**Comment by dmgower** [comment]
Sure!
 
https://forecast.gower.st/film?/?titleId=1810894&ter-id=UK&source=gsa

also: rentrak number (from screenshot): 881610
